package me.blog.hgl1002.lboard.expression.nodes;

public enum Operator {
	NONE,
	PLUS, MINUS, NOT, INVERT,
	INCREMENT_LEFT, INCREMENT_RIGHT, DECREMENT_LEFT, DECREMENT_RIGHT,

	ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION, MOD,
	SHIFT_LEFT, SHIFT_RIGHT,
	COMPARE_GREATER, COMPARE_SMALLER, COMPARE_GREATER_OR_EQUAL, COMPARE_SMALLER_OR_EQUAL,
	EQUALS, NOT_EQUALS,
	BITWISE_AND, BITWISE_OR, BITWISE_XOR,
	LOGICAL_AND, LOGICAL_OR,

	CONDITION,

	ASSIGNMENT, ASSIGNMENT_ADDITION, ASSIGNMENT_SUBTRACTION, ASSIGNMENT_MULTIPLICATION, ASSIGNMENT_DIVISION, ASSIGNMENT_MOD,
	ASSIGNMENT_SHIFT_LEFT, ASSIGNMENT_SHIFT_RIGHT, ASSIGNMENT_AND, ASSIGNMENT_OR, ASSIGNMENT_XOR,
	COMMA
}
